export const list = {
  offers: [
    {
      price: 0.5,
      spaces: 50,
      upTo: 25000,
      type: "UI Developer Solo Practice",
      name: {
        practice: true,
        preInterview: false,
      },
      effortType: "part-time",
      effortHours: 1,
      canPairProgram: false,
      daysOfAttendance: 0,
      basicRecommendation: true,
      sealDealRecommendation: { paid: true },
    },
    {
      price: 1,
      spaces: 50,
      upTo: 50000,
      type: "UI Developer Solo Practice And Pre Interview",
      name: {
        practice: true,
        preInterview: true,
      },
      effortType: "part-time",
      effortHours: 1,
      canPairProgram: true,
      daysOfAttendance: 0.5,
      basicRecommendation: true,
      sealDealRecommendation: { paid: false },
    },
    {
      price: 1,
      spaces: 25,
      upTo: 50000,
      type: "Front End Developer Solo Practice",
      name: {
        practice: true,
        preInterview: false,
      },
      effortType: "part-time",
      effortHours: 2,
      canPairProgram: false,
      daysOfAttendance: 0,
      basicRecommendation: true,
      sealDealRecommendation: { paid: true },
    },
    {
      price: 2,
      spaces: 25,
      upTo: 100000,
      type: "Front End Developer Solo Practice And Pre Interview",
      name: {
        practice: true,
        preInterview: true,
      },
      effortType: "full-time",
      effortHours: 2,
      canPairProgram: true,
      daysOfAttendance: 1,
      basicRecommendation: true,
      sealDealRecommendation: { paid: false },
    },
    {
      price: 2,
      spaces: 1,
      upTo: 100000,
      type: "Business Front End Developer Solo Practice",
      name: {
        practice: true,
        preInterview: false,
      },
      effortType: "business",
      effortHours: 3,
      canPairProgram: false,
      daysOfAttendance: 0,
      basicRecommendation: true,
      sealDealRecommendation: { paid: true },
    },
    {
      price: 4,
      spaces: 1,
      upTo: 250000,
      type: "Business Front End Developer Solo Practice And Pre Interview",
      name: {
        practice: true,
        preInterview: true,
      },
      effortType: "business",
      effortHours: 3,
      canPairProgram: true,
      daysOfAttendance: 1.5,
      basicRecommendation: true,
      sealDealRecommendation: { paid: false },
    },
  ],
  basePrice: 12500,
  baseEffort: 20,
  attendanceDays: 20,
}
