export const successList = [
  {
    image: "/../public/image/marian-zburlea.jpg",
    name: "Marian Zburlea",
    wasEarning: 1000,
    currently: "Web Architect and Mentor",
    currentlyEarning: 296000,
    b: true,
    content: [
      "Beware: all you can find here is real awesomeness! This training transformation is amazing, WoW DoP is driven by a real passion for what they do and most importantly they are always ready to help and give you good hints, advices and tutorials.",
      "I couldn't be more grateful to have find this page and have met the founder in person.",
      "If you want to be a great web developer, WoW DoP is the answer! Thank you WoW DoP!",
    ],
    i: true,
  },
  {
    image: "/../public/image/iulia-malciu-business-intensive.jpg",
    wasEarning: 0,
    currently: "Front End Developer",
    currentlyEarning: 70000,
    b: true,
    name: "Iulia Malciu",
    content: [
      "Beware: all you can find here is real awesomeness! This training transformation is amazing, WoW DoP is driven by a real passion for what they do and most importantly they are always ready to help and give you good hints, advices and tutorials.",
      "I couldn't be more grateful to have find this page and have met the founder in person.",
      "If you want to be a great web developer, WoW DoP is the answer! Thank you WoW DoP!",
    ],
    i: true,
  },
  {
    image: "/../public/image/razvan-mocanu.png",
    wasEarning: 0,
    currently: "Architect Team Lead",
    currentlyEarning: 135200,
    b: true,
    name: "Raz Mocanu",
    content: [
      "Beware: all you can find here is real awesomeness! This training transformation is amazing, WoW DoP is driven by a real passion for what they do and most importantly they are always ready to help and give you good hints, advices and tutorials.",
      "I couldn't be more grateful to have find this page and have met the founder in person.",
      "If you want to be a great web developer, WoW DoP is the answer! Thank you WoW DoP!",
    ],
    i: true,
  },
   {
     image: "/../public/image/carol-enache.png",
     wasEarning: 40000,
     currently: "Senior Front-End Developer",
     currentlyEarning: 125000,
     b: true,
     name: "Carol Enache",
     content: [
       "Beware: all you can find here is real awesomeness! This training transformation is amazing, WoW DoP is driven by a real passion for what they do and most importantly they are always ready to help and give you good hints, advices and tutorials.",
       "I couldn't be more grateful to have find this page and have met the founder in person.",
       "If you want to be a great web developer, WoW DoP is the answer! Thank you WoW DoP!",
     ],
     i: true,
   },
   {
     image: "/../public/image/elena-tandara.jpg",
     wasEarning: 0,
     currently: "Senior Front-End Developer",
     currentlyEarning: 110000,
     b: true,
     name: "Elena Tandara",
     content: [
       "Beware: all you can find here is real awesomeness! This training transformation is amazing, WoW DoP is driven by a real passion for what they do and most importantly they are always ready to help and give you good hints, advices and tutorials.",
       "I couldn't be more grateful to have find this page and have met the founder in person.",
       "If you want to be a great web developer, WoW DoP is the answer! Thank you WoW DoP!",
     ],
     i: true,
   },
   {
     image: "/../public/image/maria-teodora-cotofana.jpg",
     imageN: "/../../public/image/maria-teodora-cotofana.jpg",
     wasEarning: 24000,
     currently: "Expert Front-End Developer",
     currentlyEarning: 51000,
     b: true,
     name: "Maria-Teodora Cotofana",
     content: [
       "Beware: all you can find here is real awesomeness! This training transformation is amazing, WoW DoP is driven by a real passion for what they do and most importantly they are always ready to help and give you good hints, advices and tutorials.",
       "I couldn't be more grateful to have find this page and have met the founder in person.",
       "If you want to be a great web developer, WoW DoP is the answer! Thank you WoW DoP!",
     ],
     i: true,
   },
   {
     image: "/../public/image/dorin-dumitrascuta.jpg",
     wasEarning: 10000,
     currently: "Senior Front-End Developer",
     currentlyEarning: 120000,
     b: true,
     name: "Dorin Dumitrascuta",
     content: [
       "Beware: all you can find here is real awesomeness! This training transformation is amazing, WoW DoP is driven by a real passion for what they do and most importantly they are always ready to help and give you good hints, advices and tutorials.",
       "I couldn't be more grateful to have find this page and have met the founder in person.",
       "If you want to be a great web developer, WoW DoP is the answer! Thank you WoW DoP!",
     ],
     i: true,
   },
   {
     image: "/../public/image/flavius-bohaciuc.png",
     wasEarning: 12000,
     currently: "Senior Front-End Developer",
     currentlyEarning: 65000,
     b: true,
     name: "Flavius Bohaciuc",
     content: [
       "Beware: all you can find here is real awesomeness! This training transformation is amazing, WoW DoP is driven by a real passion for what they do and most importantly they are always ready to help and give you good hints, advices and tutorials.",
       "I couldn't be more grateful to have find this page and have met the founder in person.",
       "If you want to be a great web developer, WoW DoP is the answer! Thank you WoW DoP!",
     ],
     i: true,
   },
   {
     image: "/../public/image/istvan-acs.jpg",
     wasEarning: 16000,
     currently: "Senior Front-End Developer",
     currentlyEarning: 65000,
     b: true,
     name: "Istvan Acs",
     content: [
       "Beware: all you can find here is real awesomeness! This training transformation is amazing, WoW DoP is driven by a real passion for what they do and most importantly they are always ready to help and give you good hints, advices and tutorials.",
       "I couldn't be more grateful to have find this page and have met the founder in person.",
       "If you want to be a great web developer, WoW DoP is the answer! Thank you WoW DoP!",
     ],
     i: true,
   },
   {
     image: "/../public/image/razvan-puscasu.jpg",
     wasEarning: 12000,
     currently: "Senior Front-End Developer",
     currentlyEarning: 65000,
     b: true,
     name: "Ravzan Puscasu",
     content: [
       "Beware: all you can find here is real awesomeness! This training transformation is amazing, WoW DoP is driven by a real passion for what they do and most importantly they are always ready to help and give you good hints, advices and tutorials.",
       "I couldn't be more grateful to have find this page and have met the founder in person.",
       "If you want to be a great web developer, WoW DoP is the answer! Thank you WoW DoP!",
     ],
     i: true,
   },
   {
     image: "/../public/image/cornel-cristian-filip.jpg",
     wasEarning: 24000,
     currently: "Expert Front-End Developer",
     currentlyEarning: 45000,
     b: true,
     name: "Cornel Cristian Filip",
     content: [
       "Beware: all you can find here is real awesomeness! This training transformation is amazing, WoW DoP is driven by a real passion for what they do and most importantly they are always ready to help and give you good hints, advices and tutorials.",
       "I couldn't be more grateful to have find this page and have met the founder in person.",
       "If you want to be a great web developer, WoW DoP is the answer! Thank you WoW DoP!",
     ],
     i: true,
   },
   {
     image: "/../public/image/valentina-vanu.png",
     wasEarning: 0,
     currently: "Expert Front-End Developer",
     currentlyEarning: 58000,
     b: true,
     name: "Valentina Vanu",
     content: [
       "Beware: all you can find here is real awesomeness! This training transformation is amazing, WoW DoP is driven by a real passion for what they do and most importantly they are always ready to help and give you good hints, advices and tutorials.",
       "I couldn't be more grateful to have find this page and have met the founder in person.",
       "If you want to be a great web developer, WoW DoP is the answer! Thank you WoW DoP!",
     ],
     i: true,
   },
   {
     image: "/../public/image/laurentiu-tanase.jpg",
     wasEarning: 0,
     currently: "Principal Back-End Developer",
     currentlyEarning: 124800,
     b: true,
     name: "Laurentiu Tanase",
     content: [
       "Beware: all you can find here is real awesomeness! This training transformation is amazing, WoW DoP is driven by a real passion for what they do and most importantly they are always ready to help and give you good hints, advices and tutorials.",
       "I couldn't be more grateful to have find this page and have met the founder in person.",
       "If you want to be a great web developer, WoW DoP is the answer! Thank you WoW DoP!",
     ],
     i: true,
   },
   {
     image: "/../public/image/vlasie-dragos.jpg",
     wasEarning: 0,
     currently: "Expert Web Developer",
     currentlyEarning: 60000,
     b: true,
     name: "Vlasie Dragos",
     content: [
       "Beware: all you can find here is real awesomeness! This training transformation is amazing, WoW DoP is driven by a real passion for what they do and most importantly they are always ready to help and give you good hints, advices and tutorials.",
       "I couldn't be more grateful to have find this page and have met the founder in person.",
       "If you want to be a great web developer, WoW DoP is the answer! Thank you WoW DoP!",
     ],
     i: true,
   },
   {
     image: "/../public/image/marco-pietro-carmasachi.jpg",
     wasEarning: 28000,
     currently: "Expert Web Developer",
     currentlyEarning: 60000,
     b: true,
     name: "Marco Pietro Carmasachi",

     content: [
       "Beware: all you can find here is real awesomeness! This training transformation is amazing, WoW DoP is driven by a real passion for what they do and most importantly they are always ready to help and give you good hints, advices and tutorials.",
       "I couldn't be more grateful to have find this page and have met the founder in person.",
       "If you want to be a great web developer, WoW DoP is the answer! Thank you WoW DoP!",
     ],
     i: true,
   },
   {
     image: "/../public/image/alexandru-ivanov.jpg",
     wasEarning: 35000,
     currently: "Junior Web Developer Intern",
     currentlyEarning: 35000,

     b: true,
     name: "Alexandru Ivanov",
     content: [
       "Beware: all you can find here is real awesomeness! This training transformation is amazing, WoW DoP is driven by a real passion for what they do and most importantly they are always ready to help and give you good hints, advices and tutorials.",
       "I couldn't be more grateful to have find this page and have met the founder in person.",
       "If you want to be a great web developer, WoW DoP is the answer! Thank you WoW DoP!",
     ],
     i: true,
   },
]
